sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=tensorflow 
    include:
        - python: 2.7
          env: KERAS_BACKEND=theano 
          
before_install:
    - sudo apt-get install libhdf5-serial-dev

install:
    - pip install theano
    - pip install tensorflow
    - pip install keras
    - pip install sklearn
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    - pip install h5py
    - pip install flake8

before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
    # exit-zero treates all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - python -c "from keras import backend"
    - git submodule update --init --recursive

script:
    - PYTHONPATH=$PWD:$PYTHONPATH pytest
